### ISSUE TITLE
python requirements

### ISSUE THREAD

**Issue by thopedam** [jonstephens85/instantngp-batch#1]
To make it work out of the box, the python requirements needed to be installed with
`pip install -r requirements.txt`
To make it convenient , this might be added as a first command in the batch files.

Otherwise, Thank you a lot for the files.

**Comment by shaunl666** [comment]
ok...newbie python here

I install, 
![image](https://user-images.githubusercontent.com/63021161/211710494-60c9cfa1-9689-497d-bd33-621d9e8dcaea.png)
and
![image](https://user-images.githubusercontent.com/63021161/211710532-8129d47e-cdfb-46a6-a226-f45cdde8ff28.png)
(yes..i know, i put the binaries and the nvidea download build are in the same place)

So..drag a video to nerf_video.bat
and i get 
![image](https://user-images.githubusercontent.com/63021161/211711665-1dfd5241-c0e1-4728-8971-517d098a945e.png)

I have installed python
![image](https://user-images.githubusercontent.com/63021161/211711850-28a331ab-f81c-406c-bccc-446814b9b6e8.png)

I even uninstalled python, and reinstalled, removed anaconda..same result
(obviously) the same happens with the nerf_images.bat

**Comment by jonstephens85** [comment]
Thank you for the advice. I will most likely make a "setup" batch file that runs this and then amend the documentation to let users know they need to run this the first time.

I've been slammed at work, else I would have gotten to this much sooner!

**Comment by jonstephens85** [comment]
I added a requirements install batch file as opposed to adding it to the current batches. I also documented in the readme how to install off the the requirements prior to using the binaries.
