### ISSUE TITLE
missing cv2 from numpy

### ISSUE THREAD

**Issue by shaunl666** [jonstephens85/instantngp-batch#2]
found that using this, got me the opencv module
pip install opencv-python

**Comment by jonstephens85** [comment]
You can easily install all of the modules by going to the official Instant-NGP repository, downloading the requirements.txt file, and then running this python command:

pip install -r requirements.txt

**Comment by jonstephens85** [comment]
Per suggestion from another person, I will create a batch file. I will have it done in the morning.

**Comment by shaunl666** [comment]
> Per suggestion from another person, I will create a batch file. I will have it done in the morning.
Many thanks.

the requirements.txt worked ok, but did not get cv2
i installed opencv-python to get the cv2 running
//i see behavior discrepancies between the batch file operations, directories and transforms.json, but that may just be my dir setup

**Comment by jonstephens85** [comment]
I am going to close this one. I added the requirements install batch. I tested getting cv2 running on my spare laptop without any issues. I'll re-open this thread if more people report having this issue.
