### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY fix

### ISSUE THREAD

**Issue by shaunl666** [jonstephens85/instantngp-batch#3]
at end of processing you may get 

Attempting to free memory arena while it is still in use.
Could not free memory arena: D:/a/instant-ngp/instant-ngp/dependencies/tiny-cuda-nn/include\tiny-cuda-nn/gpu_memory.h:489 cuMemAddressFree(m_base_address, m_max_size) failed with error CUDA_ERROR_INVALID_VALUE
13:46:25 ERROR    Uncaught exception: D:/a/instant-ngp/instant-ngp/dependencies/tiny-cuda-nn/include\tiny-cuda-nn/gpu_memory.h:592 cuMemSetAccess(m_base_address + m_size, n_bytes_to_allocate, &access_desc, 1) failed with error CUDA_ERROR_OUT_OF_MEMORY

![image](https://user-images.githubusercontent.com/63021161/211906201-663e0582-0017-4d58-b292-d0d251c44711.png)

The fix is to edit the transforms.json ....  reduce the "aabb_scale": 16,      to   "aabb_scale": 4,

**Comment by jonstephens85** [comment]
I suspect you are running out of VRAM. Reducing aabb_scale is one way to reduce VRAM usage. You can also use less images or reduce the resolution of each image. I suggest 1080p equivalent imagery. High megapixel images (12+ megapixels) typically do not improve the results of the NeRF.
